// ui/rsl/src/components/ui/switch.tsx
import * as SwitchPrimitives from "@radix-ui/react-switch";
import * as React from "react";

import { cn } from "@/lib/utils";

/* eslint-disable react/prop-types */

const Switch = React.forwardRef<
  React.ElementRef<typeof SwitchPrimitives.Root>,
  React.ComponentPropsWithoutRef<typeof SwitchPrimitives.Root>
>(({ className, ...props }, ref) => (
  <SwitchPrimitives.Root
    className={cn(
      "peer inline-flex h-[24px] w-[44px] shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=unchecked]:bg-input",
      className,
    )}
    {...props}
    ref={ref}
  >
    <SwitchPrimitives.Thumb
      className={cn(
        "pointer-events-none block h-5 w-5 rounded-full bg-background shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-5 data-[state=unchecked]:translate-x-0",
      )}
    />
  </SwitchPrimitives.Root>
));
Switch.displayName = SwitchPrimitives.Root.displayName;

export { Switch };

// ui/src/lib/components/ui/switch/switch.svelte
<script lang="ts">
	import { Label, Switch } from 'bits-ui';
	import { cn } from '$lib/utils.js';

	let {
		checked = $bindable(false),
		label,
		id,
		class: className
	}: {
		checked: boolean;
		label: string;
		id: string;
		class?: string;
	} = $props();
</script>

<div class="flex items-center space-x-3 my-2">
	<Switch.Root
		{id}
		bind:checked
		class={cn(
			'peer inline-flex h-[21px] min-h-[21px] w-[45px] shrink-0 cursor-pointer items-center rounded-full px-[3px] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-foreground focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-foreground data-[state=unchecked]:bg-border data-[state=unchecked]:shadow-mini-inset dark:data-[state=checked]:bg-foreground',
			className
		)}
	>
		<Switch.Thumb
			class="pointer-events-none block size-[15px] shrink-0 rounded-full bg-background transition-transform data-[state=checked]:translate-x-6 data-[state=unchecked]:translate-x-0 data-[state=unchecked]:shadow-mini dark:border dark:border-background/30 dark:bg-foreground dark:shadow-popover dark:data-[state=unchecked]:border"
		/>
	</Switch.Root>
	<Label.Root for={id} class="text-sm font-medium">{label}</Label.Root>
</div>
